### ISSUE TITLE
Version for base should be updated from (==4.7.*) to (==4.8.*) (or <4.*)

### ISSUE THREAD

**Issue by ChristopherKing42** [jtanguy/quickwebapp#1]
The current version of base is 4.8.1.0. quickwebapp should be able to depend on it. It should either depend on (==4.8._), or even better (4._), since changes in base are unlikely to break this package.

**Comment by ChristopherKing42** [comment]
Oh, and cool thing by the way.

**Comment by jtanguy** [comment]
Thanks, but that was a really quick-n-dirty hack. I might rewrite the whole thing in [servant](http://haskell-servant.github.io), and generate a GET endpoint to quickstart an API using the code as a boilerplate.

**Comment by ChristopherKing42** [comment]
If you need any extra hands, I could help a little.
